version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: coachhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: coachhub_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coachhub-network

  # Redis per caching e sessioni
  redis:
    image: redis:7-alpine
    container_name: coachhub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - coachhub-network

  # Backend API (NestJS)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: coachhub-api
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/coachhub_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret-key-change-in-production
      NEXTAUTH_SECRET: dev-nextauth-secret
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    networks:
      - coachhub-network
    command: pnpm dev

  # Frontend (Next.js)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    container_name: coachhub-web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: dev-nextauth-secret
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - coachhub-network
    command: pnpm dev

  # Nginx Reverse Proxy (production-like)
  nginx:
    image: nginx:alpine
    container_name: coachhub-nginx
    restart: unless-stopped
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - coachhub-network

volumes:
  postgres_data:
  redis_data:

networks:
  coachhub-network:
    driver: bridge
